### PR TITLE
About us page

### LINKED ISSUE #31: About us page?
I think it'd be cute to write a little quip about ourselves? Just an extra page, we can put a photo of ourselves and maybe a little lion king character and a quip. would love some opinions on it, i think it'd be easy enough to implement (as there is no interaction you'd just have to be able to go back to the palm reading section)

### PR DESCRIPTION
**Pull request by nsyousef**
The About Us page is complete. Please let me know if you would like me to make any changes. Otherwise, we can merge it in. If you would prefer I merge it to v2.0.0 instead of ui-v2 (the branch I originally created about-us-page off of), please let me know and I can make a new pull request. Thank you!

Closes #31

### CODE REVIEW

**Comment by phuanh004** [comment]
^ I fixed some problems, but it's hard to see ppl at the bottom. So, I think it's better to move all the profile photo with names at the bottom of each like this:

Screenshot 2023-06-05 at 4 51 30 AM

**Review by phuanh004 — COMMENTED** [review]
As the above comment

**Comment by nsyousef** [comment]
Oh I see. So like have a grid of profiles at the top of the page. And then below we would have something like what I just put in the screenshot above? Or keep it the old way (like what I had when I made the pull request)?

**Comment by phuanh004** [comment]
Having another grid and the rest of our the code on this repo is the cool
way to do I think.

**Comment by nsyousef** [comment]
Ok. yeah, I can implement the grid. What do you mean by "the rest of our the code on this repo"?

**Comment by phuanh004** [comment]
I meant having another grid on the top and keep everything else that we
have at the btm of it.

**Comment by nsyousef** [comment]
Ok. I will just leave everything else as is then and just create the grid at the top. It will look something like this (although with nicer spacing; I just made this quickly in Figma):
Screenshot 2023-06-06 at 3 43 00 PM

**Comment by nsyousef** [comment]
Alright. I added the profile grid. Let me know what you think.

**Comment by fnriv** [comment]
I think we need to put some sort of blur on the background for readability- I'm squinting a bit to read the descriptions

**Comment by nsyousef** [comment]
@fnriv Do you mean like put a box around the About Us entries? The background is already blurred, but I can add boxes around the entries if the white text is blending into the background too much.

**Comment by fnriv** [comment]
Screenshot 2023-06-06 at 11 09 55 PM
if we're able to make boxes like this then maybe? i am a little stumped on other ideas so i left a message in the slack

**Comment by fnriv** [comment]
also, i was wondering if i could do a grammar fix on the about mes.... just so it's consistent. I was showing the page to some friends and they noted that

**Comment by nsyousef** [comment]
Screenshot 2023-06-06 at 11 10 53 PM

I am trying to create boxes right now. Here is what it looks like right now. What do you think?

**Comment by fnriv** [comment]
Ohhhh that looks awesome with the blur and boxes! I guess my live version didn't show the blur. i like that 😄

**Comment by nsyousef** [comment]
Sounds good. Do you think we need to have boxes around the profiles and other things at the top too? Or just the cards at the bottom? I was also thinking of choosing a differently colored default profile picture since the current one blends into the boxes a lot.

And sure, I can go through and make the grammar more consistent.

**Comment by fnriv** [comment]
I can do the grammar if you want no problem! If you send me the blurbs I'll edit them in like 20 minutes. 

Also, I'm not sure- it might be too crowded but the font still blends in. Maybe one big box for all the profiles? Not sure how that would look.

And @henryzhang03 @dolivares11 just not able to send a photo in time? it would be nice if we could all have some sort of photo (but if they don't maybe you can choose an animal photo that matches their favorite animal hehe)

**Comment by nsyousef** [comment]
Ok. The blurbs are all in `source/assets/images/profile_images/json/aboutprofiles.json`.

Yeah, I can do one big box for all the profiles at the top if you want. Or did you mean one big box that goes all the way down the page and encompasses the title, the profile grid at the top, and the individual profiles below?

Sounds good. I can look for photos of their favorite animals as well, unless they want to send their own profiles.

I also tried putting a black border around the profiles. I think it helps with the default image:
Screenshot 2023-06-07 at 12 21 24 AM

**Comment by nsyousef** [comment]
This is what it looks like with a box around the profile grid:
Screenshot 2023-06-07 at 12 29 35 AM

**Comment by nsyousef** [comment]
I have committed the current version I have of the About Us page. It includes the big box around the profile grid at the top, but this box will be relatively easy to remove if enough people prefer to go without it.

**Comment by henryzhang03** [comment]
i prefer without the box around the profile pics

**Comment by phuanh004** [comment]
Yup, without the box looks good

**Comment by nsyousef** [comment]
Alright. I have removed the box from around the profile grid at the top of the page.

**Review by henryzhang03 — APPROVED** [review]
looks good to merge

**Pull request merged**
