### PR TITLE
Add diagram

### PR DESCRIPTION
**Pull request by Christby**

### CODE REVIEW

**Review by nsyousef — CHANGES_REQUESTED** [review]
Looks good. Just a couple of pointers:

1. The JSDoc for the addImageToChat() function does not describe what the parameters width and height are for. You might want to add some comments about those. Judging by how your code looked, it seems like they take numbers and then set the image width and height to those numbers in px. You might want to specify in your comments that they are in the unit px and they only take numbers, not strings with units so people don't try to pass, say "3rem" in as the width or height.
2. Line 578 of main.js contains commented out code. Please delete it if it is not needed.

**Comment by Christby** [comment]
> Looks good. Just a couple of pointers:
> 
> 1. The JSDoc for the addImageToChat() function does not describe what the parameters width and height are for. You might want to add some comments about those. Judging by how your code looked, it seems like they take numbers and then set the image width and height to those numbers in px. You might want to specify in your comments that they are in the unit px and they only take numbers, not strings with units so people don't try to pass, say "3rem" in as the width or height.
> 2. Line 578 of main.js contains commented out code. Please delete it if it is not needed.

Got it, I will fix them now

**Comment by henryzhang03** [comment]
@Christby this PR will update with your latest changes

**Review by henryzhang03 — APPROVED** [review]
same comments as nick

**Comment by henryzhang03** [comment]
@Christby @MichaelYe48 also, Michael you can review this as well, as your issue will be closed by this PR. I linked both the add palm illustration and the issue @MichaelYe48 made to this PR. Once its closed, both will be closed

**Review by MichaelYe48 — APPROVED** [review]
This is good. Good job resolving the issue I had when reviewing the website.

**Comment by Christby** [comment]
@nsyousef Can you have a final check?

**Review by nsyousef — APPROVED** [review]
Looks good!

**Pull request merged**
