### PR TITLE
Second attempt at PR for Large Refactor

### LINKED ISSUE #25: Custom Dialogue Integration
Currently, our chat asks a series of hardcoded questions. For example, Q1 might be "Do you have the sun line", but then Q2 from our site won't use the response from the user for what Q2 should be. If I answer "yes" to Q1, I still get "Do you have the moon line", not "Blah blah blah, do you have the moon line". Let's make it more personal and interactive instead of a questionnaire by incorporating responses into our website's dialogue.

Possible implementation features that I think might be very cool is to create an AI api key and incorporate the response from the AI into our dialogue. For example, if user says "yes" to "Do you have the sun line", we call the AI API saying "I have the sun line, what does this mean", then take the response from the API, append it to the beginning of the next string before asking "Do you have the moon line".

### PR DESCRIPTION
**Pull request by henryzhang03**
Did lots of refactoring, please review code to understand current flow. Closes #25

### CODE REVIEW

**Review by MichaelYe48 — APPROVED** [review]
This version fulfills everything to my satisfaction

**Review by dolivares11 — APPROVED** [review]
looks good to me

**Comment by lemangomeister** [comment]
Looks good

**Review by lemangomeister — APPROVED** [review]
looks good

**Review by nsyousef — APPROVED** [review]
Looks good to me!

**Pull request merged**
