### PR TITLE
added animation and font

### PR DESCRIPTION
**Pull request by ChayPark**
I re-implemented the animation and font using version 2.0.0.

### CODE REVIEW

**Comment by phuanh004** [comment]
@ChayPark The delay for incoming chat is not needed, it is bad in terms of UX, Please get rid of that and change only the font, I already made the chat animation without that.

**Comment by phuanh004** [comment]
https://github.com/cse110-sp23-group3/cse110-sp23-group3/commit/4a804af46dbc6f57fe38e97ac52067338a67e209

**Comment by phuanh004** [comment]
Also, follow the commit structure that we are using right now. `feat:` for new feature, or `fix:` if fixing something

**Comment by dolivares11** [comment]
Yeah like Anh said the loading for even beginning phrases seems a little unnecessary. I think the user would get annoyed with having to wait for every single chat to load.

**Pull request closed without merging**
