### PR TITLE
feat: navbar responsiveness

### PR DESCRIPTION
**Pull request by MichaelYe48**
-basic mouse hover function so sidebar expands when engaged 
-removed bad comment syntax in main.css
-noticed/deleted unnecessary aside element in index.html

### CODE REVIEW

**Review by nsyousef — APPROVED** [review]

**Review by phuanh004 — CHANGES_REQUESTED** [review]
Please merge to v2-ui or v2

**Comment by MichaelYe48** [comment]
there are conflicts merging to V2 or V2-ui so we can just use the changes here as a reference for the future

**Comment by phuanh004** [comment]
Even if it conflicts, make a PR to v.2.0.0 since the file change is too big compared between v2 and main. I cannot track all the things that you changed

**Comment by MichaelYe48** [comment]
The PR should be updated now to v.2.0.0.

**Pull request closed without merging**
